trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: my-machine
steps:
  - checkout: self

  - powershell: |
      docker run --rm `
        -v "$(System.DefaultWorkingDirectory):/repo" `
        -w /repo `
        -e GIT_AUTHOR_NAME="azure-devops-bot" `
        -e GIT_AUTHOR_EMAIL="yulukeitor@gmail.com" `
        -e GIT_COMMITTER_NAME="azure-devops-bot" `
        -e GIT_COMMITTER_EMAIL="yulukeitor@gmail.com" `
        -e GITHUB_TOKEN="$(GH_TOKEN)" `
        ghcr.io/semantic-release/semantic-release:latest
    displayName: 'Run semantic-release (PowerShell)'
